### PR TITLE
Added optional socket.handshake.auth.auth_token token path for socket io v3

### PR DESCRIPTION
**Pull request by gruffT**
Tests not amended as would require socket.io v3 upgrade in package.json which would not be backwardly compatible.

### CODE REVIEW

**Comment by adcentury** [comment]
@gruffT Thanks for PR.

But I don't know how to pass `socket.handshake.auth.auth_token` from client. Can you modify the README.md to add this feature?

**Comment by gruffT** [comment]
Hi adcentury, I've updated that now. It's a simple replacement of auth for query in the client connection options. This will only work with v3 clients. I can update the library test to v3 but it will break v2 tests so I thought it better not to do that. Cheers

**Comment by adcentury** [comment]
LGTM.

**Comment by adcentury** [comment]
@gruffT I have merged this PR. Sorry I forgot to tell you that you can modify `pakcage.json` to add your name and email in contributors. Feel free to create a new PR for it. :)

**Pull request merged**
